### ISSUE TITLE
`TS` does not display Index as the first column

### ISSUE THREAD

**Issue by matcauthon49** [xKDR/TSx.jl#1]
When a `TS` object is viewed, if `ts.index != 1` then the Index is not the first column displayed. If the `TS` contains a large enough number of columns, then the index is not displayed at all in the terminal.

**Comment by matcauthon49** [comment]
With the new model there is no index field, so the index is the first column by default.

**Comment by chiraganand** [comment]
@matcauthon49 Put the commit reference in which this was fixed.
