### ISSUE TITLE
Formula for `pctchange` can't handle negative values.

### ISSUE THREAD

**Issue by codetalker7** [xKDR/TSx.jl#105]
Currently, the formula for `pctchange` being used is the following. 

$$
\dfrac{b - a}{a}
$$

Above, we are calculating the percent change from $a$ to $b$. However, this formula doesn't seem to be valid when $a < 0$; for instance, if $b > a$, then the percentage change should be positive, but the above formula returns something negative.

Instead, the following should be used.

$$
\dfrac{b - a}{|a|}
$$

**Comment by chiraganand** [comment]
> Currently, the formula for `pctchange` being used is the following.
> 
> b−aa
> 
> Above, we are calculating the percent change from a to b. However, this formula doesn't seem to be valid when a<0; for instance, if b>a, then the percentage change should be positive, but the above formula returns something negative.
> 
> Instead, the following should be used.
> 
> b−a|a|

This looks good to me. Shouldn't we be multiplying by 100?
