### ISSUE TITLE
add functionalities to subset to allow one-end slicing

### ISSUE THREAD

**Issue by Frank-III** [xKDR/TSx.jl#30]
add more functionalities for subset to allow 
```julia
subset(ts,:, Date(2007, 2, 1))
#or 
subset(ts,Date(2007, 2, 1),:)
```
otherwise user have to know the first index or last index of the time series

**Comment by Frank-III** [comment]
Should I open a PR as it is just a few lines of code?

**Comment by chiraganand** [comment]
> add more functionalities for subset to allow
> 
> ```julia
> subset(ts,:, Date(2007, 2, 1))
> #or 
> subset(ts,Date(2007, 2, 1),:)
> ```

Yes, both are good.

> otherwise user have to know the first index or last index of the time series

The same `getindex()` methods could also be defined so that one can do `ts[:, Date(2007)]` and `ts[Date(20007), :]`.

> Should I open a PR as it is just a few lines of code?

Yes, always good to have this. :)
