### ISSUE TITLE
`apply` fails to correctly resample using `Dates.Week`

### ISSUE THREAD

**Issue by matcauthon49** [xKDR/TSx.jl#43]
`TS.apply()` fails to correctly resample weekly data. Consider the following dataset:

```julia
julia> ts_daily_1
(360 x 1) TS with Date Index

 Index       data      
 Date        Float64   
───────────────────────
 2007-01-01  -0.790931
 2007-01-02   1.45561
 2007-01-03  -0.496326
 2007-01-04  -2.00011
     ⋮           ⋮
 2007-12-23   0.459265
 2007-12-24   0.744704
 2007-12-25   0.583233
 2007-12-26   0.104833
       352 rows omitted
```

The following operation outputs an incorrect result:

```julia
julia> ts_weekly = apply(ts_daily_1, Dates.Week(12), first)
(5 x 1) TS with Date Index

 Index       data_first 
 Date        Float64    
────────────────────────
 2007-01-01   -0.790931
 2007-01-29   -1.81454
 2007-04-23   -0.427515
 2007-07-16   -0.678125
 2007-10-08   -0.236422
```

Instead of resampling by 12 weeks each, the first box is only 4 weeks.

**Comment by ValentinKaisermayer** [comment]
I think this just due to the way Julia's rounding works, [see](https://docs.julialang.org/en/v1/stdlib/Dates/#Rounding-Epoch).
For more fine-grained control an interface based on an `AbstractVector{<:TimeType}` could be implemented. Were the vector would specify the boundaries of the cells over which to aggregate.

**Comment by chiraganand** [comment]
> I think this just due to the way Julia's rounding works, [see](https://docs.julialang.org/en/v1/stdlib/Dates/#Rounding-Epoch). For more fine-grained control an interface based on an `AbstractVector{<:TimeType}` could be implemented. Were the vector would specify the boundaries of the cells over which to aggregate.

Yes, like they do in [xts endpoints](https://rdrr.io/cran/xts/man/endpoints.html). This gives us more control over converting the timestamps into the desired frequencies to avoid such issues.

**Comment by chiraganand** [comment]
Since `endpoints()` is now implemented `apply()` should make use of it.
