### ISSUE TITLE
Implement `endpoints()` method

### ISSUE THREAD

**Issue by chiraganand** [xKDR/TSx.jl#51]
To locate points of `Index` given a particular frequency.

Interface to be similar to [R xts](https://rdrr.io/cran/xts/man/endpoints.html):
```julia
endpoints(ts::TS, on::Union{String, Symbol}, k::Int=1)
```

**Comment by ValentinKaisermayer** [comment]
I think `on` should be a function. If one supplies `Dates.month`, it simply could be used to detect the change of the integer it returns, which would specify the edge location.

**Comment by ValentinKaisermayer** [comment]
For standard time periods this is practically the same as using `:month` as a string or symbol, however, it leaves the user more freedom.

**Comment by chiraganand** [comment]
> I think `on` should be a function. If one supplies `Dates.month`, it simply could be used to detect the change of the integer it returns, which would specify the edge location.

Yes, this is a good idea. One primary method which accepts a function as an argument: `endpoints(::TS, ::Function, ::Int)` which gets called by `endpoints(ts::TS, on::Union{Symbol, String}, k::Int)` based on the value of `on`.

**Comment by chiraganand** [comment]
Added methods for individual `Dates.Period` types and test cases in 36ad04f3e84f4f54352c36c9a3cc00db25254b6e.

**Comment by chiraganand** [comment]
Macro time types are being handled currently. Intraday timestamps need to be done.

**Comment by chiraganand** [comment]
Have changed the interface to more Julia like in b7e5b0b: `endpoints(datetimes, Month(1))` while keeping the flexible `endpoints(::DateTime, on::Function, k::Int)` interface.

With this commit b7e5b0b the methods work on all `Dates.Period` types from `Year` till `Nanosecond` but the function fails when one supplies a regular series with a periodicity different than 1. Similarly, it also fails for irregular series (no consistent periodicity).

So we have 3 use cases to handle here:
1. Regular series with periodicity as a single period. Example: `Month(1)` or `Minute(1)`.
2. Regular series with periodicity greater than 1. Example: `Month(2)` or `Minute(10)`.
3. Irregular series with no consistent gap between two consecutive observations.

Case 1 is being handled currently but what should be the expectations for Case 2 and 3?

For example, for a given series `xxx` with periodicity of 2 minutes, xts in R does the following which seems correct. They are creating 3 minutely groups starting from the first timestamp:
```R
> xxx
                        [,1]
2022-09-27 13:21:06.941    1
2022-09-27 13:23:06.941    2
2022-09-27 13:25:06.941    3
2022-09-27 13:27:06.941    4
2022-09-27 13:29:06.941    5
2022-09-27 13:31:06.941    6
2022-09-27 13:33:06.941    7
2022-09-27 13:35:06.941    8
2022-09-27 13:37:06.941    9
2022-09-27 13:39:06.941   10
2022-09-27 13:41:06.941   11

> xxx[endpoints(xxx, on="minutes", k=3)]
                        [,1]
2022-09-27 13:23:06.941    2
2022-09-27 13:25:06.941    3
2022-09-27 13:29:06.941    5
2022-09-27 13:31:06.941    6
2022-09-27 13:35:06.941    8
2022-09-27 13:37:06.941    9
2022-09-27 13:41:06.941   11
```

For this case, I am not sure how to group the timestamps using 3 minutes (`Minute(3)`) which is required as `on` parameter to `endpoints(::DateTime, on::Function, ::Int)` method.
