### ISSUE TITLE
Keep a single primary method for renaming columns

### ISSUE THREAD

**Issue by chiraganand** [xKDR/TSx.jl#54]
Currently, there are two methods for `rename!()` and both of them contain the same function body. One of them should be calling the other to reduce costs of maintaining two methods.

```julia
rename!(ts::TS, colnames::AbstractVector{String})
rename!(ts::TS, colnames::AbstractVector{Symbol})
```

**Comment by ValentinKaisermayer** [comment]
The interface of `DataFrames.jl` is also much richer than only remaining by a single vector. https://dataframes.juliadata.org/stable/lib/functions/#DataFrames.rename

**Comment by chiraganand** [comment]
> The interface of `DataFrames.jl` is also much richer than only remaining by a single vector. https://dataframes.juliadata.org/stable/lib/functions/#DataFrames.rename

Right. Eventually, TSx should support the full interface. Is there any specific one you are looking for? @ValentinKaisermayer

**Comment by chiraganand** [comment]
> The interface of `DataFrames.jl` is also much richer than only remaining by a single vector. https://dataframes.juliadata.org/stable/lib/functions/#DataFrames.rename

Referenced in #61.
