### ISSUE TITLE
`TimeArray` conversion

### ISSUE THREAD

**Issue by ayushpatnaikgit** [xKDR/TSx.jl#56]
We should be able to make a `TS` object into a `TimeArray` whenever possible, and vice versa. 
For example:
```julia
using Dates
dates = collect(Date(2008):Year(1):Date(2010))
ts = TS(1:3, dates)
TimeArray(ts) # Doesn't work 
```
Perhaps `TimeArray(ts::TS)` can be put in `TimeSeries.jl` and `TS(ts::TimeArray)` can be in `TSx`

**Comment by chiraganand** [comment]
Conversion will work once Tables.jl interfaces are built. There won't be a need to treat TimeArray specially.

**Comment by chiraganand** [comment]
This was done as part of #23.
