### ISSUE TITLE
Add documentation and test cases for colnames argument in constructor

### ISSUE THREAD

**Issue by chiraganand** [xKDR/TSx.jl#62]
#47 added code for having `colnames` as a keyword argument for the constructors. The documentation and test cases need to be updated to reflect this change.

**Comment by Tumon2001** [comment]
```TS(coredata::AbstractArray{T,2}, colnames=:auto) where {T} ``` in line 271 isn't getting called when only coredata and colnames are given as input parameters to TS. It is conflicting with the ```TS(coredata::AbstractArray{T,2}, index::AbstractVector{V}, colnames=:auto) where {T, V} ``` function in line 277 as colnames is being treated as an index vector. So it would be good if the functions could be modified to allow ```colnames``` as a keyword argument.

**Comment by chiraganand** [comment]
> `TS(coredata::AbstractArray{T,2}, colnames=:auto) where {T} ` in line 271 isn't getting called when only coredata and colnames are given as input parameters to TS. It is conflicting with the `TS(coredata::AbstractArray{T,2}, index::AbstractVector{V}, colnames=:auto) where {T, V} ` function in line 277 as colnames is being treated as an index vector. So it would be good if the functions could be modified to allow `colnames` as a keyword argument.

Yes, makes sense. I would also think that having `colnames` as keyword argument is better.
