### ISSUE TITLE
Fix getindex testing error

### ISSUE THREAD

**Issue by chiraganand** [xKDR/TSx.jl#63]
Log from CI build:
```
getindex(): Test Failed at /home/runner/work/TSx.jl/TSx.jl/test/getindex.jl:36
  Expression: unique(Dates.yearmonth.(TSx.index(ts[y, m]))) == [(2007, 3)]
   Evaluated: Tuple{Int64, Int64}[] == [(2007, 3)]
Stacktrace:
 [1] top-level scope
   @ /opt/hostedtoolcache/julia/1.7.3/x64/share/julia/stdlib/v1.7/Test/src/Test.jl:445
 [2] include(fname::String)
   @ Base.MainInclude ./client.jl:451
 [3] macro expansion
   @ ~/work/TSx.jl/TSx.jl/test/runtests.jl:15 [inlined]
 [4] macro expansion
   @ /opt/hostedtoolcache/julia/1.7.3/x64/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
 [5] top-level scope
   @ ~/work/TSx.jl/TSx.jl/test/runtests.jl:15
getindex(): Error During Test at /home/runner/work/TSx.jl/TSx.jl/test/runtests.jl:14
  Got exception outside of a @test
  LoadError: MethodError: no method matching test_types(::Float64)
  Closest candidates are:
    test_types(!Matched::TS) at ~/work/TSx.jl/TSx.jl/test/getindex.jl:3
  Stacktrace:
    [1] top-level scope
      @ ~/work/TSx.jl/TSx.jl/test/getindex.jl:47
    [2] include(fname::String)
      @ Base.MainInclude ./client.jl:451
    [3] macro expansion
      @ ~/work/TSx.jl/TSx.jl/test/runtests.jl:15 [inlined]
    [4] macro expansion
      @ /opt/hostedtoolcache/julia/1.7.3/x64/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
    [5] top-level scope
      @ ~/work/TSx.jl/TSx.jl/test/runtests.jl:15
    [6] include(fname::String)
      @ Base.MainInclude ./client.jl:451
    [7] top-level scope
      @ none:6
    [8] eval
      @ ./boot.jl:373 [inlined]
    [9] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:268
   [10] _start()
      @ Base ./client.jl:495
  in expression starting at /home/runner/work/TSx.jl/TSx.jl/test/getindex.jl:47
  ```

**Comment by codetalker7** [comment]
Regarding this issue, I don't think subsetting with dates is working as the documentation claims.

For example, consider this code (I've taken this from the user guide: https://xkdr.github.io/TSx.jl/dev/user_guide/#Indexing-and-subsetting)

```julia
using CSV, DataFrames, TSx, Dates
filename = joinpath(dirname(pathof(TSx)),
           "..", "docs", "src", "assets", "sample_daily.csv")
df = CSV.read(filename, DataFrame)
ts = TS(df)

# this returns an empty TS object
ts[Year(2007), Month(1)]
```

The output of `ts[Year(2007), Month(1)]` should contain 31 entries, but I'm getting an empty TS object: 
```julia
(0 x 1) TS with Date Index
```

Is there some bug in the code, or has something changed?

**Comment by chiraganand** [comment]
Nothing has changed, though, the comparison of the `filter` function isn't really matching equal types. Fixing it.

**Comment by chiraganand** [comment]
That's why the test cases need to be fixed.

**Comment by codetalker7** [comment]
> Nothing has changed, though, the comparison of the `filter` function isn't really matching equal types. We need to match like this: `yearmonth(x) == (y.value, m.value)`

@chiraganand I'm a bit confused; do we need to change the code or the test case? When I make this fix in the code, the test case is passing.

**Comment by codetalker7** [comment]
On a side note, the test in `tests/getindex.jl:47` is also failing. `t = ts[i, j]` is returning a float, and hence `test_types(t)` doesn't make sense.

**Comment by chiraganand** [comment]
> > Nothing has changed, though, the comparison of the `filter` function isn't really matching equal types. We need to match like this: `yearmonth(x) == (y.value, m.value)`
> 
> @chiraganand I'm a bit confused; do we need to change the code or the test case? When I make this fix in the code, the test case is passing.

The code is incorrect in this case but the test is correct.

> On a side note, the test in `tests/getindex.jl:47` is also failing. `t = ts[i, j]` is returning a float, and hence `test_types(t)` doesn't make sense.

The reason to test the type of the output would be to make sure the type isn't being changed somewhere. But, yes, this much one can rely on Julia and DataFrames to not test the types in such cases. :)

**Comment by codetalker7** [comment]
Can we close this issue now?
