### ISSUE TITLE
Remove assets from docs

### ISSUE THREAD

**Issue by ValentinKaisermayer** [xKDR/TSx.jl#64]
I think it is not wise to put data into a repository. Although it us pretty small.

**Comment by chiraganand** [comment]
Yes, those assets are being used for documentation. Don't know what the best practice is for storing sample data sets?

**Comment by ViralBShah** [comment]
The right way is to supply these as artifacts. The https://github.com/simeonschaub/ArtifactUtils.jl package shows you how to do that.

Otherwise, host them on a github pages repo in this org and `download` as needed.

**Comment by ViralBShah** [comment]
Since this package is not yet registered, it would be nice to see if the datasets can be removed from the git history altogether (by rewriting the history) - since it otherwise makes the git history bulky going forward.

**Comment by chiraganand** [comment]
I'll explore the two options. It shouldn't be hard to rewrite history.
