### ISSUE TITLE
Can `apply` work for all user provided functions?

### ISSUE THREAD

**Issue by matcauthon49** [xKDR/TSx.jl#7]
The `fun` argument may be a function which only works for scalars or only works for vectors (`AbstractVector`). The implementation of `apply()` needs to figure out whether to use broadcasting operator or not. Or, perhaps create different `apply()` methods for both cases.

**Comment by chiraganand** [comment]
`apply()` now works for both kind of functions: returning scalar and vector output. It also works for 2-dimenstional arrays now.
refs 16fe9a5787377d96282d8057be23434b5f94f126 2459db9b5770faf00926d491fd002d2d194e84ec
